export const REQUEST_NEWS_LIST = "REQUEST_NEWS_LIST";
export const PUT_NEWS_LIST = "PUT_NEWS_LIST";
export const PUT_PENDING_NEWS_LIST = "PUT_PENDING_NEWS_LIST";
export const PUT_ERROR_NEWS_LIST = "PUT_ERROR_NEWS_LIST";

export enum actionTypes {
  REQUEST_NEWS_LIST = "REQUEST_NEWS_LIST",
  PUT_NEWS_LIST = "PUT_NEWS_LIST",
  PUT_PENDING_NEWS_LIST = "PUT_PENDING_NEWS_LIST",
  PUT_ERROR_NEWS_LIST = "PUT_ERROR_NEWS_LIST",
}
